-- MySQL Script generated by MySQL Workbench
-- 06/04/14 15:59:09
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kms` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `kms` ;

-- -----------------------------------------------------
-- Table `kms`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kms`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kms`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kms`.`location` (
  `id` INT NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_location_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_location_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `kms`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kms`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kms`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(40) NOT NULL,
  `lastname` VARCHAR(40) NOT NULL,
  `username` VARCHAR(40) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `date_create` DATE NOT NULL,
  `state` TINYINT(1) NOT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_location1_idx` (`location_id` ASC),
  CONSTRAINT `fk_user_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `kms`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kms`.`privilege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kms`.`privilege` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `path` VARCHAR(50) NOT NULL,
  `image` VARCHAR(50) NOT NULL,
  `width` DOUBLE NOT NULL,
  `height` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kms`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kms`.`permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `privilege_id` INT NOT NULL,
  `state` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_permission_user_idx` (`user_id` ASC),
  INDEX `fk_permission_privilege1_idx` (`privilege_id` ASC),
  CONSTRAINT `fk_permission_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `kms`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permission_privilege1`
    FOREIGN KEY (`privilege_id`)
    REFERENCES `kms`.`privilege` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kms`.`action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kms`.`action` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `activity` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kms`.`audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kms`.`audit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `hour` TIME NOT NULL,
  `action_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_audit_action1_idx` (`action_id` ASC),
  INDEX `fk_audit_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_audit_action1`
    FOREIGN KEY (`action_id`)
    REFERENCES `kms`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audit_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kms`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kms`.`conductor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kms`.`conductor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(40) NOT NULL,
  `lastname` VARCHAR(40) NOT NULL,
  `cedula` VARCHAR(20) NOT NULL,
  `carnet` VARCHAR(45) NOT NULL,
  `state` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kms`.`type_vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kms`.`type_vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `capacity` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kms`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kms`.`vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plate` VARCHAR(20) NOT NULL,
  `no_input` VARCHAR(20) NOT NULL,
  `odom_current` DOUBLE NOT NULL,
  `city_id` INT NOT NULL,
  `conductor_id` INT NOT NULL,
  `type_vehicle_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vehicle_city1_idx` (`city_id` ASC),
  INDEX `fk_vehicle_conductor1_idx` (`conductor_id` ASC),
  INDEX `fk_vehicle_type_vehicle1_idx` (`type_vehicle_id` ASC),
  CONSTRAINT `fk_vehicle_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `kms`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_conductor1`
    FOREIGN KEY (`conductor_id`)
    REFERENCES `kms`.`conductor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_type_vehicle1`
    FOREIGN KEY (`type_vehicle_id`)
    REFERENCES `kms`.`type_vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kms`.`eds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kms`.`eds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eds_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_eds_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `kms`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kms`.`tanking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kms`.`tanking` (
  `id` INT NOT NULL,
  `gallon_volume` DOUBLE NOT NULL,
  `price_billing` DOUBLE NOT NULL,
  `date` DATE NOT NULL,
  `vehicle_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `eds_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tanking_vehicle1_idx` (`vehicle_id` ASC),
  INDEX `fk_tanking_user1_idx` (`user_id` ASC),
  INDEX `fk_tanking_eds1_idx` (`eds_id` ASC),
  CONSTRAINT `fk_tanking_vehicle1`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `kms`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tanking_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kms`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tanking_eds1`
    FOREIGN KEY (`eds_id`)
    REFERENCES `kms`.`eds` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kms`.`fuel_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kms`.`fuel_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vehicle_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `origin` VARCHAR(40) NOT NULL,
  `target` VARCHAR(40) NOT NULL,
  `odom1` DOUBLE NOT NULL,
  `odom2` DOUBLE NOT NULL,
  `kms` DOUBLE NOT NULL,
  `date` DATE NOT NULL,
  `hour` TIME NOT NULL,
  `state` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fuel_log_vehicle1_idx` (`vehicle_id` ASC),
  INDEX `fk_fuel_log_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_fuel_log_vehicle1`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `kms`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fuel_log_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kms`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kms`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kms`.`activity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kms`.`justifi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kms`.`justifi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kms` DOUBLE NOT NULL,
  `remark` VARCHAR(150) NOT NULL,
  `activity_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `vehicle_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_justifi_activity1_idx` (`activity_id` ASC),
  INDEX `fk_justifi_user1_idx` (`user_id` ASC),
  INDEX `fk_justifi_vehicle1_idx` (`vehicle_id` ASC),
  CONSTRAINT `fk_justifi_activity1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `kms`.`activity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_justifi_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kms`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_justifi_vehicle1`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `kms`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
